@host=http://localhost:5188

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZDQ5MDRmZi1hM2RhLTQzMTYtYmZlMi0wNGViZTA3OGMwZTUiLCJnaXZlbl9uYW1lIjoiT21hciIsImZhbWlseV9uYW1lIjoiVG9ycmVzIiwianRpIjoiMzc5ZjMzZTEtNTg4NS00Nzc0LWI1MzgtODI3YWQ2MGRiOWU4IiwiZXhwIjoxNjk1Nzk2NDE4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.MEO3uX9E5NqvwWzvlAdyJnAaqmiFyWDCKN9CGdSlh4s