@host=http://localhost:5188

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Omar",
    "lastName": "Torres",
    "email": "omtorresr@gmail.com",
    "password": "Amiko1234"
}